---
version: 2
sources:
- name: "samples.tpch"
  database: "samples"
  schema: "tpch"
  config:
    enabled: true
  tables:
  - name: "customer"
    columns:
    - name: "c_custkey"
      dataType:
        type: "Bigint"
    - name: "c_name"
      dataType:
        type: "String"
    - name: "c_address"
      dataType:
        type: "String"
    - name: "c_nationkey"
      dataType:
        type: "Bigint"
    - name: "c_phone"
      dataType:
        type: "String"
    - name: "c_acctbal"
      dataType:
        type: "Decimal"
    - name: "c_mktsegment"
      dataType:
        type: "String"
    - name: "c_comment"
      dataType:
        type: "String"
  - name: "orders"
    columns:
    - name: "o_orderkey"
      dataType:
        type: "Bigint"
    - name: "o_custkey"
      dataType:
        type: "Bigint"
    - name: "o_orderstatus"
      dataType:
        type: "String"
    - name: "o_totalprice"
      dataType:
        type: "Decimal"
    - name: "o_orderdate"
      dataType:
        type: "Date"
    - name: "o_orderpriority"
      dataType:
        type: "String"
    - name: "o_clerk"
      dataType:
        type: "String"
    - name: "o_shippriority"
      dataType:
        type: "Integer"
    - name: "o_comment"
      dataType:
        type: "String"
